### ISSUE TITLE
Library crashing when providing .m3u8 file

### ISSUE THREAD

**Issue by mohitkapoor1230** [pankaj89/MasterExoPlayer#19]
The library is crashing when I provide .m3u8 file format. Below is the crash logs:

FATAL EXCEPTION: ExoPlayerImplInternal:Handler
Process: com.------, PID: 9969
java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.source.BaseMediaSource.prepareSourceInternal(com.google.android.exoplayer2.upstream.TransferListener)"
at com.google.android.exoplayer2.source.BaseMediaSource.prepareSource(BaseMediaSource.java:140)
at com.google.android.exoplayer2.source.CompositeMediaSource.prepareChildSource(CompositeMediaSource.java:101)
at com.google.android.exoplayer2.source.LoopingMediaSource.prepareSourceInternal(LoopingMediaSource.java:76)
at com.google.android.exoplayer2.source.BaseMediaSource.prepareSource(BaseMediaSource.java:140)
at com.google.android.exoplayer2.ExoPlayerImplInternal.prepareInternal(ExoPlayerImplInternal.java:398)
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:285)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:246)
at android.os.HandlerThread.run(HandlerThread.java:67)

Please help to resolve this

**Comment by ahmadrushdie** [comment]
same here did you get a solution ?
